---
title: "Searchable Codebook for AllofUs"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Searchable Codebook for AllofUs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- <style> -->
<!-- body { -->
<!--   max-width: 95vw !important; -->
<!-- } -->
<!-- </style> -->
```{r setup, echo = FALSE}
library(allofus)
```

```{r, echo = FALSE, out.width = "100%"}
   cols = c("concept_code", "concept_id", "concept_name", "concept_class_id",
            "form_name", "field_type", "fild_label", "choices")

    DT::datatable(allofus::aou_codebook[,cols],
                  rownames = FALSE,
                  filter = 'top',
                  plugins = "ellipsis",
                  extensions = 'Buttons',
                  options = list(
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                    pageLength = 20,
                    # scrollX = TRUE,
                    # scrollCollapse = TRUE,
                    columnDefs = list(list(
                      targets = c(6,7),
                      render = DT::JS("$.fn.dataTable.render.ellipsis( 20, false )")
                    ))
                  )) |>
                    DT::formatStyle(table = _, columns = cols, fontSize = '80%')
```

